apiVersion: v1
kind: Service
metadata:
  labels:
    app: dspy-sample-api
    environment: production
  name: dspy-sample-api-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: dspy-sample-api
  type: ClusterIP
